In [1]:
import numpy as np
import pandas as pd

In [ ]:
import kagglehub
from kagglehub import KaggleDatasetAdapter
file_path = "IMDB Dataset.csv"
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "lakshmi25npathi/imdb-dataset-of-50k-movie-reviews",
  file_path,
)

/tmp/ipython-input-1839773794.py:4: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'imdb-dataset-of-50k-movie-reviews' dataset.

In [ ]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
# lowercasing
df['review'] = df['review'].str.lower()

In [ ]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. <br /><br />the...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [ ]:
# remove HTML tags
import re
def remove_HTML(text):
  pattern = re.compile('<.*?>')
  return pattern.sub('r',text)

In [ ]:
df['review'] = df['review'].apply(remove_HTML)

In [ ]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. rrthe filming t...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [ ]:
# remove URL's
import re
def remove_urls(text):
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    cleaned_text = url_pattern.sub('', text)
    return cleaned_text
sample_text = "Visit our site at https://www.geeksforgeeks.org/ for tutorials, or check out www.google.com"
cleaned_output = remove_urls(sample_text)

print(cleaned_output)

Visit our site at  for tutorials, or check out

In [ ]:
# remove punctution
import string

In [ ]:
exclude = string.punctuation

In [ ]:
def remove_punctuation(text):
  for char in exclude:
    text = text.replace(char,"")
  return text

In [ ]:
sentence = "This .is ,a sentennce with /punctuation?"

In [ ]:
print(remove_punctuation(sentence))

This is a sentennce with punctuation

In [ ]:
def remove_punc(text):       #### faster way
  return text.translate(str.maketrans("","",exclude))

In [ ]:
remove_punc(sentence)

'This is a sentennce with punctuation'

In [ ]:
import kagglehub
from kagglehub import KaggleDatasetAdapter
file_path = "test.csv"
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "arkhoshghalb/twitter-sentiment-analysis-hatred-speech",
  file_path,
)

/tmp/ipython-input-3832501833.py:4: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Downloading from https://www.kaggle.com/api/v1/datasets/download/arkhoshghalb/twitter-sentiment-analysis-hatred-speech?dataset_version_number=1&file_name=test.csv...

100%|██████████| 675k/675k [00:00<00:00, 78.7MB/s]

Extracting zip of test.csv...
First 5 records:       id                                              tweet
0  31963  #studiolife #aislife #requires #passion #dedic...
1  31964   @user #white #supremacists want everyone to s...
2  31965  safe ways to heal your #acne!!    #altwaystohe...
3  31966  is the hp and the cursed child book up for res...
4  31967    3rd #bihday to my amazing, hilarious #nephew...

In [ ]:
df['tweet'] = df['tweet'].apply(remove_punc)

In [ ]:
df

          id                                              tweet
0      31963  studiolife aislife requires passion dedication...
1      31964   user white supremacists want everyone to see ...
2      31965  safe ways to heal your acne    altwaystoheal h...
3      31966  is the hp and the cursed child book up for res...
4      31967    3rd bihday to my amazing hilarious nephew el...
...      ...                                                ...
17192  49155  thought factory leftright polarisation trump u...
17193  49156  feeling like a mermaid ð hairflip neverread...
17194  49157  hillary campaigned today in ohioomg amp used w...
17195  49158  happy at work conference right mindset leads t...
17196  49159  my   song so glad free download  shoegaze newm...

[17197 rows x 2 columns]

In [ ]:
# chat word treatment

chat_words = {
    "A3": "Anytime, Anywhere, Anyplace",
    "ADIH": "Another Day In Hell",
    "AFK": "Away From Keyboard",
    "AFAIK": "As Far As I Know",
    "ASAP": "As Soon As Possible",
    "ASL": "Age, Sex, Location",
    "ATK": "At The Keyboard",
    "ATM": "At The Moment",
    "BAE": "Before Anyone Else",
    "BAK": "Back At Keyboard",
    "BBL": "Be Back Later",
    "BBS": "Be Back Soon",
    "BFN": "Bye For Now",
    "B4N": "Bye For Now",
    "BRB": "Be Right Back",
    "BRUH": "Bro",
    "BRT": "Be Right There",
    "BSAAW": "Big Smile And A Wink",
    "BTW": "By The Way",
    "BWL": "Bursting With Laughter",
    "CSL": "Can’t Stop Laughing",
    "CU": "See You",
    "CUL8R": "See You Later",
    "CYA": "See You",
    "DM": "Direct Message",
    "FAQ": "Frequently Asked Questions",
    "FC": "Fingers Crossed",
    "FIMH": "Forever In My Heart",
    "FOMO": "Fear Of Missing Out",
    "FR": "For Real",
    "FWIW": "For What It's Worth",
    "FYP": "For You Page",
    "FYI": "For Your Information",
    "G9": "Genius",
    "GAL": "Get A Life",
    "GG": "Good Game",
    "GMTA": "Great Minds Think Alike",
    "GN": "Good Night",
    "GOAT": "Greatest Of All Time",
    "GR8": "Great!",
    "HBD": "Happy Birthday",
    "IC": "I See",
    "ICQ": "I Seek You",
    "IDC": "I Don’t Care",
    "IDK": "I Don't Know",
    "IFYP": "I Feel Your Pain",
    "ILU": "I Love You",
    "ILY": "I Love You",
    "IMHO": "In My Honest/Humble"
}

In [ ]:
def chat_conversion(text):
  new_text = []
  for w in text.split():
    if w.upper() in chat_words:
      new_text.append(chat_words[w.upper()])
    else:
      new_text.append(w)
  return " ".join(new_text)

In [ ]:
chat_conversion("GN all")

'Good Night all'

In [ ]:
# spelling correction
from textblob import TextBlob

In [ ]:
incorrect_text = "Ceertain conditions duriing seveal ggenerations aree modified in the saame maner"
TextBlob(incorrect_text).correct().string

'Certain conditions during several generations are modified in the same manner'

In [ ]:
# removing stop words
from nltk.corpus import stopwords

In [ ]:
import nltk
nltk.download('stopwords')

In [ ]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [ ]:
def remove_stopwords(text):
  new_text = []
  for word in text.split():
    if word in stopwords.words("english"):
      new_text.append("")
    else:
      new_text.append(word)
  x = new_text[:]
  new_text.clear()
  return " ".join(x)

In [ ]:
remove_stopwords("Hello I am Indrajit")

'Hello I  Indrajit'

In [ ]:
import kagglehub
from kagglehub import KaggleDatasetAdapter
file_path = "IMDB Dataset.csv"
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "lakshmi25npathi/imdb-dataset-of-50k-movie-reviews",
  file_path,
)

/tmp/ipython-input-1839773794.py:4: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'imdb-dataset-of-50k-movie-reviews' dataset.

In [ ]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [ ]:
df['review'].apply(remove_stopwords)

KeyboardInterrupt:

In [ ]:
# handling emojis

# Source - https://stackoverflow.com/a/33417311
# Posted by jfs, modified by community. See post 'Timeline' for change history
# Retrieved 2026-02-24, License - CC BY-SA 3.0

#!/usr/bin/env python
import re

def remove_emoji(text):
  emoji_pattern = re.compile("["
          u"\U0001F600-\U0001F64F"  # emoticons
          u"\U0001F300-\U0001F5FF"  # symbols & pictographs
          u"\U0001F680-\U0001F6FF"  # transport & map symbols
          u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                            "]+", flags=re.UNICODE)
  return emoji_pattern.sub(r'', text) # no emoji

In [ ]:
remove_emoji("Hello how are u?😁")

'Hello how are u?'

In [ ]:
import emoji
print(emoji.demojize("Hello how are u?😁"))

Hello how are u?:beaming_face_with_smiling_eyes:

# Tokenization

## Using the split function

In [ ]:
# word tokenization
sent1 = "i am going to delhi"
sent1.split()

['i', 'am', 'going', 'to', 'delhi']

In [ ]:
# sentence tokenization
sent2 = 'I am going to delhi.  I will stay there for 3 days. Let\'s hope the trip to be great'
sent2.split(".")

['I am going to delhi',
 '  I will stay there for 3 days',
 " Let's hope the trip to be great"]

In [ ]:
# problem with split function
sent3 = 'I am going to delhi!'
sent3.split()

['I', 'am', 'going', 'to', 'delhi!']

In [ ]:
sent4 = "Where do think I should go? I have 3 day holiday"
sent4.split('.')

['Where do think I should go? I have 3 day holiday']

## Regular Expression

In [ ]:
import re
tokens = re.findall("[\w']+",sent3)
tokens

<>:2: SyntaxWarning: invalid escape sequence '\w'
<>:2: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipython-input-10139330.py:2: SyntaxWarning: invalid escape sequence '\w'
  tokens = re.findall("[\w']+",sent3)

['I', 'am', 'going', 'to', 'delhi']

In [ ]:
text = "Lorem Ipsum is simply dummy text of the printing and typesetting industry? Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."

In [ ]:
sentences = re.compile('[.!?] ').split(text)
sentences

['Lorem Ipsum is simply dummy text of the printing and typesetting industry',
 "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."]

## NLTK

In [ ]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [ ]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
sent_tokenize(text)

['Lorem Ipsum is simply dummy text of the printing and typesetting industry?',
 "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."]

In [1]:
sent5 = "I have a Ph.D in A.I"
sent6 = "We're here to help! mail us at nks@gmail.com"
sent7 = "A 5km ride cost $10.50"

In [ ]:
word_tokenize(sent5)

['I', 'have', 'a', 'Ph.D', 'in', 'A.I']

In [ ]:
word_tokenize(sent6)

['We',
 "'re",
 'here',
 'to',
 'help',
 '!',
 'mail',
 'us',
 'at',
 'nks',
 '@',
 'gmail.com']

In [ ]:
word_tokenize(sent7)

['A', '5km', 'ride', 'cost', '$', '10.50']

## spacy

In [2]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [4]:
doc1 = nlp(sent5)
doc2 = nlp(sent6)
doc3 = nlp(sent7)
doc4 = nlp(sent1)

In [7]:
doc1

I have a Ph.D in A.I

In [6]:
type(doc1)

spacy.tokens.doc.Doc

In [ ]:
for word in doc1:
  print(word)

I
have
a
Ph
.
D
in
A.I

In [ ]:
for word in doc2:
  print(word)

We
're
here
to
help
!
mail
us
at
nks@gmail.com

In [ ]:
for word in doc3:
  print(word)

A
5
km
ride
cost
$
10.50

In [ ]:
for word in doc4:
  print(word)

i
am
going
to
delhi

# Stemming

In [ ]:
from nltk.stem.porter import PorterStemmer

In [ ]:
ps = PorterStemmer()
def stem_words(text):
  return " ".join([ps.stem(word) for word in text.split()])

In [ ]:
sample = "walk walks walking walked"
stem_words(sample)

'walk walk walk walk'

In [ ]:
ps.stem("Walking")

'walk'

In [ ]:
ps.stem("Walked")

'walk'

In [ ]:
paragraph = "Paragraphs are the building blocks of papers. Many students define paragraphs in terms of length: a paragraph is a group of at least five sentences, a paragraph is half a page long, etc. In reality, though, the unity and coherence of ideas among sentences is what constitutes a paragraph. A paragraph is defined as “a group of sentences or a single sentence that forms a unit” (Lunsford and Connors 116). Length and appearance do not determine whether a section in a paper is a paragraph. For instance, in some styles of writing, particularly journalistic styles, a paragraph can be just one sentence long. Ultimately, a paragraph is a sentence or group of sentences that support one main idea. In this handout, we will refer to this as the “controlling idea,” because it controls what happens in the rest of the paragraph."

In [ ]:
paragraph

'Paragraphs are the building blocks of papers. Many students define paragraphs in terms of length: a paragraph is a group of at least five sentences, a paragraph is half a page long, etc. In reality, though, the unity and coherence of ideas among sentences is what constitutes a paragraph. A paragraph is defined as “a group of sentences or a single sentence that forms a unit” (Lunsford and Connors 116). Length and appearance do not determine whether a section in a paper is a paragraph. For instance, in some styles of writing, particularly journalistic styles, a paragraph can be just one sentence long. Ultimately, a paragraph is a sentence or group of sentences that support one main idea. In this handout, we will refer to this as the “controlling idea,” because it controls what happens in the rest of the paragraph.'

In [ ]:
stem_words(paragraph)

'paragraph are the build block of papers. mani student defin paragraph in term of length: a paragraph is a group of at least five sentences, a paragraph is half a page long, etc. in reality, though, the uniti and coher of idea among sentenc is what constitut a paragraph. a paragraph is defin as “a group of sentenc or a singl sentenc that form a unit” (lunsford and connor 116). length and appear do not determin whether a section in a paper is a paragraph. for instance, in some style of writing, particularli journalist styles, a paragraph can be just one sentenc long. ultimately, a paragraph is a sentenc or group of sentenc that support one main idea. in thi handout, we will refer to thi as the “control idea,” becaus it control what happen in the rest of the paragraph.'

# Lemmatization

In [ ]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:
from nltk.stem import WordNetLemmatizer
wnl = WordNetLemmatizer()

sentence = "He was runing and eating at same time. He has bad habit of swimming after playing long hours in the Sun."
punctuations = "?:!.,;"
sentence_words = nltk.word_tokenize(sentence)

for word in sentence_words:
  if word in punctuations:
    sentence_words.remove(word)

sentence_words
print("{0:20}{1:20}".format("Word","Lemma"))
for word in sentence_words:
  print("{0:20}{1:20}".format(word,wnl.lemmatize(word,pos='v')))

Word                Lemma
He                  He
was                 be
runing              run
and                 and
eating              eat
at                  at
same                same
time                time
He                  He
has                 have
bad                 bad
habit               habit
of                  of
swimming            swim
after               after
playing             play
long                long
hours               hours
in                  in
the                 the
Sun                 Sun