# **Data Acquisition**

In [1]:
import pandas as pd
import numpy as np
import requests

In [2]:
url = "https://api.themoviedb.org/3/genre/movie/list?language=en"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJmYTFhNTliOTgxNTYyZjBjMGM0OTVkYmU2YjliMGI0MCIsIm5iZiI6MTc0MTA4NTA2My42MjQsInN1YiI6IjY3YzZkOTg3YzczZjE5OWY2YTkwN2Q4ZiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.864XyLmrVoHDUxnXRGZnuEz0GBaNxUc-qhGvJalmbtE"
}

response = requests.get(url, headers=headers)

print(response.json())

{'genres': [{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 80, 'name': 'Crime'}, {'id': 99, 'name': 'Documentary'}, {'id': 18, 'name': 'Drama'}, {'id': 10751, 'name': 'Family'}, {'id': 14, 'name': 'Fantasy'}, {'id': 36, 'name': 'History'}, {'id': 27, 'name': 'Horror'}, {'id': 10402, 'name': 'Music'}, {'id': 9648, 'name': 'Mystery'}, {'id': 10749, 'name': 'Romance'}, {'id': 878, 'name': 'Science Fiction'}, {'id': 10770, 'name': 'TV Movie'}, {'id': 53, 'name': 'Thriller'}, {'id': 10752, 'name': 'War'}, {'id': 37, 'name': 'Western'}]}

In [3]:
genres = pd.json_normalize(response.json(),record_path=['genres'])
genres

       id             name
0      28           Action
1      12        Adventure
2      16        Animation
3      35           Comedy
4      80            Crime
5      99      Documentary
6      18            Drama
7   10751           Family
8      14          Fantasy
9      36          History
10     27           Horror
11  10402            Music
12   9648          Mystery
13  10749          Romance
14    878  Science Fiction
15  10770         TV Movie
16     53         Thriller
17  10752              War
18     37          Western

In [4]:
# url = "https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=4720"

# headers = {
#     "accept": "application/json",
#     "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJmYTFhNTliOTgxNTYyZjBjMGM0OTVkYmU2YjliMGI0MCIsIm5iZiI6MTc0MTA4NTA2My42MjQsInN1YiI6IjY3YzZkOTg3YzczZjE5OWY2YTkwN2Q4ZiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.864XyLmrVoHDUxnXRGZnuEz0GBaNxUc-qhGvJalmbtE"
# }

# response = requests.get(url, headers=headers)

# print(response)

In [5]:
# df = pd.json_normalize(response.json(),record_path=['results'])

In [6]:
# df[[ 'title','overview','genre_ids']]

In [7]:
# status_code = 200
# page = 1
# while status_code == 200:
#   url = f"https://api.themoviedb.org/3/movie/top_rated?language=en-US&page={page}"

#   headers = {
#       "accept": "application/json",
#       "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJmYTFhNTliOTgxNTYyZjBjMGM0OTVkYmU2YjliMGI0MCIsIm5iZiI6MTc0MTA4NTA2My42MjQsInN1YiI6IjY3YzZkOTg3YzczZjE5OWY2YTkwN2Q4ZiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.864XyLmrVoHDUxnXRGZnuEz0GBaNxUc-qhGvJalmbtE"
#   }

#   response = requests.get(url, headers=headers)
#   status_code = response.status_code
#   page += 1
#   print(page,response)

In [8]:
status_code = 200
page = 1
top_movies = []
while status_code == 200:
  url = f"https://api.themoviedb.org/3/movie/top_rated?language=en-US&page={page}"

  headers = {
      "accept": "application/json",
      "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJmYTFhNTliOTgxNTYyZjBjMGM0OTVkYmU2YjliMGI0MCIsIm5iZiI6MTc0MTA4NTA2My42MjQsInN1YiI6IjY3YzZkOTg3YzczZjE5OWY2YTkwN2Q4ZiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.864XyLmrVoHDUxnXRGZnuEz0GBaNxUc-qhGvJalmbtE"
  }

  response = requests.get(url, headers=headers)
  status_code = response.status_code
  # df = pd.json_normalize(response.json(),record_path=['results'])[[ 'title','overview','genre_ids']]
  # pd.merge(top_movies,df)
  movie_data = response.json().get("results")
  # print(page,response)
  if status_code == 200:
    top_movies.extend(movie_data)
  # top_movies.extend(movie_data)
  page += 1

In [9]:
# top_movies

In [10]:
top_movies = pd.json_normalize(top_movies)[["title","overview","genre_ids"]]
top_movies

,title,overview,genre_ids
0,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"[18, 80]"
1,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","[18, 80]"
2,The Godfather Part II,In the continuing saga of the Corleone crime f...,"[18, 80]"
3,Schindler's List,The true story of how businessman Oskar Schind...,"[18, 36, 10752]"
4,12 Angry Men,The defense and the prosecution have rested an...,[18]
...,...,...,...
9995,Zookeeper,Kindhearted Griffin Keyes is one of the best-l...,"[35, 10749, 10751]"
9996,The Man Who Killed Hitler and Then the Bigfoot,Decades after serving in WWII and assassinatin...,"[18, 12, 14, 878, 10752]"
9997,Serial Teachers,With only 12 percent of its pupils obtaining t...,[35]
9998,The Dead Don't Die,"In the sleepy town of Centerville, the lives o...","[35, 27]"
9999,Await Further Instructions,A dysfunctional family awake on Christmas morn...,[27]

# **Data Marging**

In [11]:
genres.head()

   id       name
0  28     Action
1  12  Adventure
2  16  Animation
3  35     Comedy
4  80      Crime

In [12]:
top_movies.head()

,title,overview,genre_ids
0,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"[18, 80]"
1,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","[18, 80]"
2,The Godfather Part II,In the continuing saga of the Corleone crime f...,"[18, 80]"
3,Schindler's List,The true story of how businessman Oskar Schind...,"[18, 36, 10752]"
4,12 Angry Men,The defense and the prosecution have rested an...,[18]

In [13]:
genre_dict = dict(zip(genres['id'],genres['name']))

In [14]:
top_movies["genres"] = top_movies['genre_ids'].apply(
    lambda id_list : ",".join([genre_dict.get(id,"Unknown") for id in id_list])
)

In [15]:
top_movies.drop("genre_ids",axis=1,inplace=True)

In [16]:
# Final DataSet
top_movies

,title,overview,genres
0,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"Drama,Crime"
1,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","Drama,Crime"
2,The Godfather Part II,In the continuing saga of the Corleone crime f...,"Drama,Crime"
3,Schindler's List,The true story of how businessman Oskar Schind...,"Drama,History,War"
4,12 Angry Men,The defense and the prosecution have rested an...,Drama
...,...,...,...
9995,Zookeeper,Kindhearted Griffin Keyes is one of the best-l...,"Comedy,Romance,Family"
9996,The Man Who Killed Hitler and Then the Bigfoot,Decades after serving in WWII and assassinatin...,"Drama,Adventure,Fantasy,Science Fiction,War"
9997,Serial Teachers,With only 12 percent of its pupils obtaining t...,Comedy
9998,The Dead Don't Die,"In the sleepy town of Centerville, the lives o...","Comedy,Horror"
9999,Await Further Instructions,A dysfunctional family awake on Christmas morn...,Horror

In [17]:
# top_movies.to_csv("top_movies.csv",index=False)

In [18]:
top_movies_df = top_movies.copy()

# **Lowercasing**

In [19]:
top_movies_df['overview'] = top_movies_df['overview'].str.lower()

In [20]:
top_movies_df['overview'].head(2)

0    imprisoned in the 1940s for the double murder ...
1    spanning the years 1945 to 1955, a chronicle o...
Name: overview, dtype: object

# **Remove Punctution**

In [21]:
import string
exclude = string.punctuation
def remove_punctution(text):
  return text.translate(str.maketrans("","",exclude))

In [22]:
top_movies_df['overview'] = top_movies_df['overview'].apply(remove_punctution)

In [23]:
top_movies_df['overview'].sample(2)

3097    two colleagues become stranded on a deserted i...
9163    amidst a sea of litigation two new york city d...
Name: overview, dtype: object

# **Spelling Correction**

In [24]:
# from textblob import TextBlob
# def spell_correction(text):
#   return TextBlob(text).correct().string

In [25]:
# top_movies_df['overview'] = top_movies_df['overview'].apply(spell_correction)

In [26]:
# top_movies_df['overview'].sample(2)

# **Removing Stop Words**

In [27]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
# stop_words = set(stopwords.words('english'))
def remove_stopwords(text):
  new_text = []
  for word in text.split():
    if word in stopwords.words("english"):
      new_text.append("")
    else:
      new_text.append(word)
  x = new_text[:]
  new_text.clear()
  return " ".join(x)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [28]:
top_movies_df['overview'] = top_movies_df['overview'].apply(remove_stopwords)

In [29]:
top_movies_df['overview'].head(2)

0    imprisoned   1940s   double murder   wife   lo...
1    spanning  years 1945  1955  chronicle   fictio...
Name: overview, dtype: object

# **Remove Emoji**

In [30]:
pip install emoji

Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 10.1 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.15.0

In [31]:
import emoji
# print(emoji.demojize("Hello how are u?😁"))
# top_movies_df
top_movies_df["overview"] = top_movies_df["overview"].apply(emoji.demojize)

In [32]:
top_movies_df.head(2)

,title,overview,genres
0,The Shawshank Redemption,imprisoned 1940s double murder wife lo...,"Drama,Crime"
1,The Godfather,spanning years 1945 1955 chronicle fictio...,"Drama,Crime"

# **Tokenize**

## **Using NLTK**

In [33]:
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [34]:
top_movies_df['overview'].apply(word_tokenize)

0       [imprisoned, 1940s, double, murder, wife, love...
1       [spanning, years, 1945, 1955, chronicle, ficti...
2       [continuing, saga, corleone, crime, family, yo...
3       [true, story, businessman, oskar, schindler, s...
4       [defense, prosecution, rested, jury, filing, j...
                              ...
9995    [kindhearted, griffin, keyes, one, bestloved, ...
9996    [decades, serving, wwii, assassinating, adolf,...
9997    [12, percent, pupils, obtaining, baccalaureate...
9998    [sleepy, town, centerville, lives, number, int...
9999    [dysfunctional, family, awake, christmas, morn...
Name: overview, Length: 10000, dtype: object

## **Using Spacy**

In [35]:
import spacy

nlp = spacy.load("en_core_web_sm")

def spacy_tokenize(text):
  return nlp(text)

In [36]:
top_movies_df['overview'] = top_movies_df['overview'].apply(spacy_tokenize)

In [37]:
top_movies_df.head(2)

,title,overview,genres
0,The Shawshank Redemption,"(imprisoned, , 1940s, , double, murder, ...","Drama,Crime"
1,The Godfather,"(spanning, , years, 1945, , 1955, , chronic...","Drama,Crime"

In [38]:
type(top_movies_df['overview'][0])

spacy.tokens.doc.Doc

# **Stemming**

In [39]:
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()
def stem_words(lst):
  return " ".join([ps.stem(str(word)) for word in lst])

In [40]:
top_movies_df['overview'].apply(stem_words).head(2)

0    imprison    1940    doubl murder    wife    lo...
1    span   year 1945   1955   chronicl    fiction ...
Name: overview, dtype: object

# **Lemmatization**

In [41]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [42]:
from nltk.stem import WordNetLemmatizer
wnl = WordNetLemmatizer()

def wordnlemmatizer(lst):
  return " ".join([wnl.lemmatize(str(word),pos='v') for word in lst])

In [43]:
top_movies_df['overview'].apply(wordnlemmatizer)

0       imprison    1940s    double murder    wife    ...
1       span   years 1945   1955   chronicle    fictio...
2          continue saga    corleone crime family   yo...
3         true story    businessman oskar schindler sa...
4         defense    prosecution   rest    jury   file...
                              ...
9995    kindhearted griffin key   one    bestloved car...
9996    decades   serve   wwii   assassinate adolf hit...
9997       12 percent    pupils obtain   baccalaureate...
9998       sleepy town   centerville   live    number ...
9999      dysfunctional family awake   christmas morni...
Name: overview, Length: 10000, dtype: object

In [44]:
top_movies_df['overview']

0       (imprisoned,   , 1940s,   , double, murder,   ...
1       (spanning,  , years, 1945,  , 1955,  , chronic...
2       (  , continuing, saga,   , corleone, crime, fa...
3       ( , true, story,   , businessman, oskar, schin...
4       ( , defense,   , prosecution,  , rested,   , j...
                              ...
9995    (kindhearted, griffin, keyes,  , one,   , best...
9996    (decades,  , serving,  , wwii,  , assassinatin...
9997    (  , 12, percent,   , pupils, obtaining,  , ba...
9998    (  , sleepy, town,  , centerville,  , lives,  ...
9999    ( , dysfunctional, family, awake,  , christmas...
Name: overview, Length: 10000, dtype: object

# **Remove "s" from Year Using Regex**

In [45]:
import re
def sentence_clening(text):
  return re.sub(r'(\d+)s\b', r'\1', text)